### ISSUE TITLE
OSX: "iotcl: inappropriate ioctl for device"

### ISSUE THREAD

**Issue by cj1128** [lelandbatey/blink#4]
os: OS X Yosimeite, Version 10.10.5(X86_64)
when I run blink, I got the error in title.

**Comment by lelandbatey** [comment]
@fate-lovely Unfortunately, `blink` currently only supports Linux, not OS X. As I don't personally own a Mac, I don't have a good way to develop this. I invite you or anyone else to implement this on OS X though!
